-- Criação do banco e suas tabelas
-- Contexto: Loja de produtos de Informática

-- CRIAR BANCO DE DADOS
CREATE DATABASE LOJA_INFORMATICA;

-- USAR A DATABASE SELECIONADA
USE LOJA_INFORMATICA;

--  CRIAR TABELA DE PRODUTOS
CREATE TABLE PRODUTOS(
ID INT AUTO_INCREMENT PRIMARY KEY,
NOME VARCHAR(255) NOT NULL,
VALOR DECIMAL(10,2) NOT NULL,
FILIAL VARCHAR(50) NOT NULL,
QUANTIDADE_ESTOQUE INT NOT NULL,
MARCA VARCHAR(20) NOT NULL
);

-- CRIAR TABELA DE CLIENTES
CREATE TABLE CLIENTES(
ID INT AUTO_INCREMENT PRIMARY KEY,
NOME VARCHAR(50) NOT NULL,
SOBRENOME VARCHAR(50) NOT NULL,
EMAIL VARCHAR(200) NOT NULL,
WHATSAPP VARCHAR(50) NOT NULL,
ESTADO VARCHAR(50) NOT NULL,
TELEFONE VARCHAR(20) NOT NULL,
SEXO ENUM('M','F','I') NOT NULL
);

-- CRIAR TABELA DE VENDAS REALIZADAS
CREATE TABLE VENDA_REALIZADA(
ID INT AUTO_INCREMENT PRIMARY KEY,
DATA_VENDA DATE NOT NULL,
QUANTIDADE INT NOT NULL,
PRODUTO_ID INT NOT NULL,
CLIENTE_ID INT NOT NULL,
FOREIGN KEY(PRODUTO_ID) REFERENCES PRODUTOS(ID),
FOREIGN KEY(CLIENTE_ID) REFERENCES CLIENTES(ID)
);

-- NOVA TABELA: FORNECEDORES
CREATE TABLE FORNECEDORES (
ID INT PRIMARY KEY,
NOME VARCHAR(100) NOT NULL,
ENDERECO VARCHAR(255) NOT NULL,
TELEFONE VARCHAR(20) NOT NULL,
EMAIL VARCHAR(200) NOT NULL,
MARCA_PRINCIPAL VARCHAR(20) NOT NULL,
ESTADO CHAR(2) NOT NULL
);