-- CONSULTA DE VENDA REALIZADA
SELECT * FROM VENDA_REALIZADA;
-- CONSULTA DE PRODUTOS
SELECT * FROM PRODUTOS;
-- CONSULTA DE CLIENTES
SELECT * FROM CLIENTES;
SELECT DISTINCT(MARCA) FROM PRODUTOS;

-- JOINS DE TABELAS
-- CONSULTA COM O VALOR TOTAL VENDIDO DAS TABELAS PRODUTOS, CLIENTES E VENDA REALIZADA
SELECT 
VR.DATA_VENDA,
VR.QUANTIDADE,
P.NOME AS NOME_PRODUTO,
P.MARCA_PRINCIPAL AS MARCA,
P.VALOR AS VALOR_PRODUTO,
CONCAT(C.NOME, ' ', C.SOBRENOME) AS NOME_CLIENTE,
C.ESTADO AS ESTADO,
(VR.QUANTIDADE * P.VALOR) AS TOTAL_VENDIDO
FROM 
VENDA_REALIZADA VR
JOIN 
PRODUTOS P ON VR.PRODUTO_ID = P.ID
JOIN 
CLIENTES C ON VR.CLIENTE_ID = C.ID;


-- VENDAS POR FORNECEDOR E QUANTIDADE DE PRODUTOS FORNECIDOS
SELECT
F.NOME AS FORNECEDOR,
F.MARCA_PRINCIPAL AS MARCA_FORNECIDA,
SUM(P.VALOR) AS VALOR_TOTAL,
SUM(P.QUANTIDADE_ESTOQUE) AS QTD_SAIDA_ESTOQUE
FROM
FORNECEDORES F
JOIN
PRODUTOS P ON F.MARCA_PRINCIPAL = P.MARCA_PRINCIPAL
GROUP BY
F.NOME, F.MARCA_PRINCIPAL;
